<?php

// RULES: https://mlocati.github.io/php-cs-fixer-configurator/#version:3.1

return [
    '@PSR2'                                       => true,
    'align_multiline_comment'                     => [
        'comment_type' => 'phpdocs_like',
    ],
    'array_indentation'                           => true,
    'array_syntax'                                => [
        'syntax' => 'short',
    ],
    'binary_operator_spaces'                      => [
        'operators' => [
            '=>' => 'align_single_space_minimal',
            '='  => 'align_single_space_minimal',
        ],
    ],
    'blank_line_after_namespace'                  => true,
    'blank_line_after_opening_tag'                => true,
    'blank_line_before_statement'                 => [
        'statements' => [
            'return',
        ],
    ],
    'braces'                                      => true,
    'cast_spaces'                                 => true,
    'class_attributes_separation'                 => ['elements' => ['method' => 'one']],
    'class_definition'                            => [
        'single_line' => true,
    ],
    'combine_consecutive_unsets'                  => true,
    'concat_space'                                => [
        'spacing' => 'one',
    ],
    'constant_case'                               => true,
    'declare_equal_normalize'                     => [
        'space' => 'single',
    ],
    'elseif'                                      => true,
    'encoding'                                    => true,
    //'final_class'                                 => false,
    'full_opening_tag'                            => true,
    'fully_qualified_strict_types'                => true,
    'function_declaration'                        => [
        'closure_function_spacing' => 'one',
    ],
    'function_typehint_space'                     => true,
    'global_namespace_import'                     => true,
    'heredoc_to_nowdoc'                           => true,
    'include'                                     => true,
    'increment_style'                             => [
        'style' => 'post',
    ],
    'indentation_type'                            => true,
    'line_ending'                                 => true,
    'list_syntax'                                 => [
        'syntax' => 'short',
    ],
    'lowercase_cast'                              => true,
    'lowercase_keywords'                          => true,
    'magic_constant_casing'                       => true,
    'method_argument_space'                       => true,
    'method_chaining_indentation'                 => true,
    'multiline_whitespace_before_semicolons'      => true,
    'native_function_casing'                      => true,
    //'new_with_braces' => true,
    'no_blank_lines_after_class_opening'          => true,
    'no_blank_lines_after_phpdoc'                 => true,
    'no_closing_tag'                              => true,
    'no_empty_comment'                            => true,
    'no_empty_phpdoc'                             => true,
    'no_empty_statement'                          => true,
    'no_extra_blank_lines'                        => [
        'tokens' => [
            'extra',
            'throw',
            'use',
            'use_trait',
        ],
    ],
    'no_leading_import_slash'                     => true,
    'no_leading_namespace_whitespace'             => true,
    'no_mixed_echo_print'                         => [
        'use' => 'echo',
    ],
    'no_multiline_whitespace_around_double_arrow' => true,
    'no_short_bool_cast'                          => true,
    'no_singleline_whitespace_before_semicolons'  => true,
    'no_spaces_after_function_name'               => true,
    'no_spaces_around_offset'                     => true,
    'no_spaces_inside_parenthesis'                => true,
    'no_trailing_comma_in_list_call'              => true,
    'no_trailing_comma_in_singleline_array'       => true,
    'no_trailing_whitespace'                      => true,
    'no_trailing_whitespace_in_comment'           => true,
    'no_unneeded_control_parentheses'             => true,
    'no_unused_imports'                           => true,
    'no_useless_return'                           => true,
    'no_whitespace_before_comma_in_array'         => true,
    'no_whitespace_in_blank_line'                 => true,
    'normalize_index_brace'                       => true,
    'not_operator_with_successor_space'           => true,
    'object_operator_without_whitespace'          => true,
    'ordered_imports'                             => [
        'sort_algorithm' => 'alpha',
    ],
    'phpdoc_add_missing_param_annotation'         => true,
    'phpdoc_align'                                => ['align' => 'left'],
    'phpdoc_indent'                               => true,
    'general_phpdoc_tag_rename'                   => ['replacements' => ['inheritDocs' => 'inheritDoc']],
    'phpdoc_inline_tag_normalizer'                => ['tags' => ['example']],
    'phpdoc_tag_type'                             => ['tags' => []],
    'phpdoc_no_access'                            => true,
    'phpdoc_no_package'                           => true,
    'phpdoc_no_useless_inheritdoc'                => true,
    'phpdoc_scalar'                               => true,
    'phpdoc_single_line_var_spacing'              => true,
    'phpdoc_summary'                              => true,
    'phpdoc_to_comment'                           => true,
    'phpdoc_trim'                                 => true,
    'phpdoc_no_alias_tag'                         => [
        'replacements' => [
            'property-read'  => 'property',
            'property-write' => 'property',
            'type'           => 'var',
            'link'           => 'see'
        ]
    ],
    'phpdoc_types'                                => true,
    'phpdoc_var_without_name'                     => true,
    'return_type_declaration'                     => true,
    'short_scalar_cast'                           => true,
    'simplified_null_return'                      => true,
    'single_blank_line_at_eof'                    => true,
    'single_blank_line_before_namespace'          => true,
    'single_class_element_per_statement'          => true,
    'single_import_per_statement'                 => true,
    'single_line_after_imports'                   => true,
    'single_line_comment_style'                   => [
        'comment_types' => [
            'hash',
        ],
    ],
    'single_quote'                                => true,
    'space_after_semicolon'                       => true,
    'standardize_not_equals'                      => true,
    'switch_case_semicolon_to_colon'              => true,
    'switch_case_space'                           => true,
    'ternary_operator_spaces'                     => true,
    'trailing_comma_in_multiline'                 => ['elements' => ['arrays']],
    'trim_array_spaces'                           => true,
    'unary_operator_spaces'                       => true,
    'visibility_required'                         => true,
    'whitespace_after_comma_in_array'             => true,
];
